import express from 'express'; import {Pool} from 'pg'; import argon2 from 'argon2'; import jwt from 'jsonwebtoken'; import {randomUUID,createHash} from 'node:crypto'; import {z} from 'zod'; import {env} from '@aibi/config'; import {logger} from '@aibi/logger'; import {AppError,unauthorized} from '@aibi/errors'; import {errorHandler} from '@aibi/http'; import {requestContext} from '@aibi/observability'; import {connectBus,publish} from '@aibi/messaging';
const app=express(); app.use(express.json({limit:'1mb'})); app.use(requestContext); const pool=new Pool({host:env.postgres.host,port:env.postgres.port,database:env.postgres.db,user:env.postgres.user,password:env.postgres.password});
async function init(){await pool.query(`CREATE EXTENSION IF NOT EXISTS pgcrypto; CREATE TABLE IF NOT EXISTS users(id uuid primary key default gen_random_uuid(),email text unique not null,password_hash text not null,first_name text,last_name text,status text not null default 'ACTIVE',created_at timestamptz not null default now()); CREATE TABLE IF NOT EXISTS organizations(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,created_at timestamptz not null default now()); CREATE TABLE IF NOT EXISTS memberships(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id),organization_id uuid not null references organizations(id),role text not null default 'OWNER',created_at timestamptz not null default now(),unique(user_id,organization_id)); CREATE TABLE IF NOT EXISTS refresh_tokens(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id),token_hash text not null,expires_at timestamptz not null,revoked_at timestamptz,created_at timestamptz not null default now());`);}
const sign=(u:any)=>jwt.sign({sub:u.id,email:u.email},env.jwtSecret,{expiresIn:env.accessTtl as any}); const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
const auth=async(req:any,_res:any,next:any)=>{try{const h=req.header('authorization')??''; if(!h.startsWith('Bearer '))throw unauthorized(); req.user=jwt.verify(h.slice(7),env.jwtSecret); next()}catch{next(unauthorized())}};
app.get('/health',(req,res)=>res.json({status:'ok',service:'identity-service'})); app.get('/ready',async(_req,res)=>{await pool.query('select 1');res.json({status:'ready'})});
app.post('/api/v1/auth/register',async(req,res,next)=>{try{const b=z.object({email:z.string().email(),password:z.string().min(8),first_name:z.string().min(1),last_name:z.string().min(1),organization_name:z.string().min(2)}).parse(req.body); const c=await pool.connect(); try{await c.query('BEGIN'); const user=(await c.query('insert into users(email,password_hash,first_name,last_name) values($1,$2,$3,$4) returning id,email,first_name,last_name',[b.email.toLowerCase(),await argon2.hash(b.password,{type:argon2.argon2id}),b.first_name,b.last_name])).rows[0]; const slug=b.organization_name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+user.id.slice(0,8); const org=(await c.query('insert into organizations(name,slug) values($1,$2) returning *',[b.organization_name,slug])).rows[0]; await c.query("insert into memberships(user_id,organization_id,role) values($1,$2,'OWNER')",[user.id,org.id]); const refresh=randomUUID(); await c.query("insert into refresh_tokens(user_id,token_hash,expires_at) values($1,$2,now()+($3||' days')::interval)",[user.id,hash(refresh),env.refreshDays]); await c.query('COMMIT'); await publish('user.created',{user_id:user.id},{producer:'identity-service'}); res.status(201).json({data:{user,organization:org,access_token:sign(user),refresh_token:refresh}})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}catch(e){next(e)}});
app.post('/api/v1/auth/login',async(req,res,next)=>{try{const b=z.object({email:z.string().email(),password:z.string()}).parse(req.body); const u=(await pool.query('select * from users where email=$1',[b.email.toLowerCase()])).rows[0]; if(!u||!(await argon2.verify(u.password_hash,b.password)))throw unauthorized('Invalid credentials'); const refresh=randomUUID(); await pool.query("insert into refresh_tokens(user_id,token_hash,expires_at) values($1,$2,now()+($3||' days')::interval)",[u.id,hash(refresh),env.refreshDays]); res.json({data:{user:{id:u.id,email:u.email,first_name:u.first_name,last_name:u.last_name},access_token:sign(u),refresh_token:refresh}})}catch(e){next(e)}});
app.post('/api/v1/auth/refresh',async(req,res,next)=>{try{const {refresh_token}=z.object({refresh_token:z.string().min(10)}).parse(req.body); const r=(await pool.query('select rt.*,u.email from refresh_tokens rt join users u on u.id=rt.user_id where token_hash=$1 and revoked_at is null and expires_at>now()',[hash(refresh_token)])).rows[0]; if(!r)throw unauthorized('Invalid refresh token'); await pool.query('update refresh_tokens set revoked_at=now() where id=$1',[r.id]); const n=randomUUID(); await pool.query("insert into refresh_tokens(user_id,token_hash,expires_at) values($1,$2,now()+($3||' days')::interval)",[r.user_id,hash(n),env.refreshDays]); res.json({data:{access_token:jwt.sign({sub:r.user_id,email:r.email},env.jwtSecret,{expiresIn:env.accessTtl as any}),refresh_token:n}})}catch(e){next(e)}});
app.post('/api/v1/auth/logout',auth,async(req:any,res,next)=>{try{if(req.body?.refresh_token)await pool.query('update refresh_tokens set revoked_at=now() where user_id=$1 and token_hash=$2',[req.user.sub,hash(req.body.refresh_token)]);res.status(204).send()}catch(e){next(e)}});
app.get('/api/v1/auth/me',auth,async(req:any,res,next)=>{try{const u=(await pool.query('select id,email,first_name,last_name,status,created_at from users where id=$1',[req.user.sub])).rows[0];res.json({data:{user:u,memberships:(await pool.query('select organization_id,role from memberships where user_id=$1',[req.user.sub])).rows}})}catch(e){next(e)}});
app.get('/api/v1/organizations',auth,async(req:any,res,next)=>{try{const rows=(await pool.query('select o.*,m.role from organizations o join memberships m on m.organization_id=o.id where m.user_id=$1 order by o.created_at desc',[req.user.sub])).rows;res.json({data:rows})}catch(e){next(e)}});
app.use(errorHandler); init().then(()=>connectBus()).then(()=>app.listen(3001,()=>logger.info('identity-service listening on 3001'))).catch(e=>{logger.error(e);process.exit(1)});
